### ISSUE TITLE
05 JULY 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#10]
## Date
5th July 2022 - 6pm BST / 1pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Catherine share metrics update
- [x] Preparation for July 14th board meeting 
- [x] Jevon and Events Group - https://github.com/finos/DEI-SIG/issues/8
  - London event group update
  - Looking for co-lead / support for Sep event 
  - DEI Event at FINOS Governing Board Meeting, 14th July
- [ ] Beeke - Plan what awards for other types of contributions (for OSSF NY)...doesn't need to be direct contributions seen on GitHub
- [ ] Rita / Lynn - plan for NY OSFF
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info
**Meeting link:**
- https://zoom.us/j/98492160513

**Meeting number:**
- 2552 137 1430

**Join by phone**
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll

**Access code:**
- 2552 137 1430

**Comment by mindthegab** [comment]
👋 hello everyone!

**Comment by alstratigos** [comment]
Hi

**Comment by beekemarie** [comment]
hi!

**Comment by mindthegab** [comment]
FYI take a look at CHAOSS DEI Events metrics - https://chaoss.community/diversity-and-inclusion-badging/

**Comment by catherinezhai** [comment]
hello

**Comment by alstratigos** [comment]
Here's the "Asks" slide to be used for the DEI update at the July 14th board meeting
[The Asks slide for FINOS board meeting.pptx](https://github.com/finos/DEI-SIG/files/9050154/The.Asks.slide.for.FINOS.board.meeting.pptx)
