### ISSUE TITLE
02 August 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/DEI-SIG#11]
## Date
02 August 2022 - 1:00 PM EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] DEI sessions/talks at OSFF NY - Dec 8th - [Call for Papers](https://events.linuxfoundation.org/open-source-finance-forum-new-york/program/cfp/?utm_medium=email&_hsmi=220268757&_hsenc=p2ANqtz-9ckbVgElIRlE_rgyKoZjab4L63oHyHAnTStzC7__fU3MHj6MTfnjNHCbzJVc34XCxig8uEZbvs1BflwFysjFVWYqtCXQ&utm_content=220268757&utm_source=hs_email) deadline Sept 12th - 
- [ ] FINOS July board meeting - presentation update (incl below main points) & next steps  
- [ ] Discuss/agree on types of contributions for Awards (to be used for OSSF NY with the end goal of increasing diversity in award recipient profiles) (Beeke)
- [ ] OKRs (target vs goal)
- [ ] AOB, Q&A & Adjourn (5mins)

## Meeting Notes
- [ ] Day event (banks getting involved.
Natwest have stepped forward (Declan O'Gorman) and they have a big DEI team, so they're collaborating with James to make this part happen). We can use their space for any activities we need. They're also happy to chip in on budget for evening event.  Everything needs to be firmed up when people return from vacation.
and evening event (zingly team organizing)
- [ ] ING also onboard. They have labs in the spitalfields area which include start ups
- [ ] Update from Jevon: Phil from GitHub / FINOS board rep might get involved in one of the events

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting info

Join Zoom Meeting
[https://zoom.us/j/98492160513](https://www.google.com/url?q=https://zoom.us/j/98492160513&sa=D&source=calendar&ust=1658750571349575&usg=AOvVaw1ITN6rZ-NGKHxK-6fK3hyP)
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by cm-howard** [comment]
Hello :hand:

**Comment by melindajoy** [comment]
hello!

**Comment by grizzwolf** [comment]
howdy - and @mcleo-d as well

**Comment by alstratigos** [comment]
Hi!

**Comment by jevonbeck** [comment]
hi

**Comment by winmorgan** [comment]
Hi everyone ✋

**Comment by TheJuanAndOnly99** [comment]
Hi

**Comment by winmorgan** [comment]
[Declan O'Gorman linkedin](https://resources.finos.org/znglist/osff-london-2022-video-recordings/?c=cG9zdDoxNzQx) [keynote from OSFF London](https://resources.finos.org/znglist/osff-london-2022-video-recordings/?c=cG9zdDoxNzQx)
