### ISSUE TITLE
06 September 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/DEI-SIG#12]
## Date
06 September 2022 - time

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Meeting time clashes with FINOS Regulation Innovation SIG. Can we find a time that does not clash with another FINOS meeting. [Community Calendar](https://www.finos.org/finos-community-calendar)
- [x] Resources for 1st time speakers: [Resource Center](https://resources.finos.org/content/first-time-conference-speakers-how-tos-with-leslie-hawthorn-of-red-hat/?finos-content=open-source-in-finance-podcast) & [Blog Post](https://www.finos.org/blog/open-source-in-finance-podcast-first-time-conference-speakers-how-tos-with-leslie-hawthorn-of-red-hat)
- [x] Tech Gateway update and SIG help needed for promotion - https://tg.zngly.com/
- [x] FINOS Community Awards and the DEI SIG - James has a clash on this meeting, but the conversation needs to start about getting the SIG involved.
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by jevonbeck** [comment]
Jevon Beckles - present

**Comment by alstratigos** [comment]
Hi.

**Comment by winmorgan** [comment]
Present

**Comment by cdeliaRH** [comment]
Cara Delia present.

**Comment by TheJuanAndOnly99** [comment]
hi
