### ISSUE TITLE
October 5th 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/DEI-SIG#13]
## Date
October 5th 2022 - 12:00 PM EST / 5PM BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] What is the plan for achieving OKR at OSFF NY in Dec?
- [x] Tech Gateway community response, impact and moving forward.
  - Brief description of the event, sponsors and sessions.
  - Who from the London community attended?
  - What were the outcomes of the event?
  - Does the SIG want to blog about the event for FINOS website?
  - Does the SIG want to represent Tech Gateway at the FINOS All Community Call on 26th October?
- [ ] FINOS Community Awards.
  - DEI SIG OSFF Awards Discussion happened on 27th September. 
  - Decision made to focus on Community Leadership Award only
  - Nominations requested by DEI SIG to FINOS Community
  - The purpose is to recognise people not recorded by data.
  - Nominations to include the person being nominated and the reason why.
  - Nominations to be voted upon by the FINOS Community using GitHub.
  - DEI SIG to feedback and engage for 8th December OSFF 
- [ ] AOB, Q&A & Adjourn (5mins)

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by mcleo-d** [comment]
Updates as communicated by Mike Wilson...

- The [Tech Gateway resource hub](https://tg.zngly.com/) is live and can be integrated into GitHub etc / used as a great way of bringing different community members and content together 
- The Campfire interviews with NatWest, LTSB and EPAM are all live too - and look great
- I am interviewing Gary from Google remotely on Monday, as part of our ‘Meet The Experts’ series and will include that in Tech Gateway too

**Comment by melindajoy** [comment]
hello

**Comment by cm-howard** [comment]
Hey 👋🏼

**Comment by mcleo-d** [comment]
Hey 👋🏻

**Comment by alstratigos** [comment]
Hi
