### ISSUE TITLE
02 November 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/DEI-SIG#15]
## Date
November 2nd 2022 - time

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x]  FINOS Community Awards.
- [x] DEI SIG OSFF Awards Discussion happened on 27th September.
  - [ ] https://github.com/finos/community/issues/213
    - Can you help socialise to the FINOS community, social media and your bank. 
  - [ ] Decision made to focus on Community Leadership Award only
  - [ ] Nominations requested by DEI SIG to FINOS Community
  - [ ] The purpose is to recognise people not recorded by data.
  - [ ] Nominations to include the person being nominated and the reason why.
  - [ ] Nominations to be decided by the FINOS DEI SIG.
  - [ ] DEI SIG to feedback and engage for 8th December OSFF
- [x] New co-chair 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by cm-howard** [comment]
Hello 👋🏼

**Comment by jevonbeck** [comment]
hi

**Comment by alstratigos** [comment]
Hi!
