### ISSUE TITLE
February 1st 2023 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#17]
## Date
February 1st 2023 - 12:00pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by mindthegab** [comment]
Given the January meeting was canceled, I would think some more concrete items for this agenda would be:

1. Brainstorming 2/3 key initiatives / concrete goals for DEI SIG (not for FINOS at large) in 2023
2. Revising operating model and responsibilities (who does what)
3. Asks / suggestions for the incoming executive sponsors Kim and Rhyddian, potentially as it aligns to existing corporate initiatives.

Just my 0.02$ @beekemarie @mcleo-d and Rita (don't see her on Github).

**Comment by beekemarie** [comment]
Thanks, Gab! + 1 on that

It would be great if we can cover who is committed to own agreed upon workstreams/initiatives as part of #2.

Looking forward to speaking to everyone tomorrow.

**Comment by alstratigos** [comment]
Hi

**Comment by cm-howard** [comment]
Hello 👍🏼

**Comment by rhyddian** [comment]
Hi.  Rhyddian Olds @ Citi

**Comment by whykay** [comment]
Hello from Dublin!

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by TheJuanAndOnly99** [comment]
Hi :)

**Comment by beekemarie** [comment]
hi

**Comment by ditomike** [comment]
Hi

**Comment by mcleo-d** [comment]
from @cm-howard : Not sure if we've ever explored but CHAOSS DEI Badging should be explored for our in person events... and once they get it rolled out for Projects to.

https://chaoss.community/diversity-and-inclusion-badging/

**Comment by mcleo-d** [comment]
## Meeting Outcomes

Reviewed 2022 SIG structure and agreed to change for 2023 if not appropriate
What are the key outcomes and what needs to be done?
Executives agreed to take outcomes and requirements to the FINOS board to move forward where needed
Find groups within FINOS Platinum and Gold memberships so we can leverage existing networks
 - Connections should be made at the point of membership and onboarding
 
Find banking links to existing external charities and bring into SIG.
Can the FINOS bank SIG groups and charities help us achieve our outcomes?
Can diverse groups of developers inside banks get involved in FINOS open source projects?

**Goal Brainstorming**
- We should iterate DEI progress between meetings and bring updates to the group.
- Increase diversity in open source through FINOS
- Invite committed FINOS members and contributors to the DEI SIG
- Increase FINOS event DEI speakers and attendees
- Find people inside firms who aren't recognised for their contributions to FINOS. 
  - How do we find and recognise these contributors?
  - How do we make FINOS a safe space for wider contribution?
- We need something to rally around that can be positively measured and delivered
  - See Big Boost Monday as first idea to iterate and test

**Question**
- What is the definition of a FINOS contributor so DEI involvement can be positively measured?

**How did people find the DEI SIG?**
- Introduced via networking at Linux Foundation event
- Introduced via OSFF London 2021 and organised a DEI roundtable as a result

## First SIG Initiative : Big Boost Monday, London

- DEI SIG to organise entry point meet-ups for the wider DEI community to meet FINOS Projects, SIGs and Maintainers
- First DEI SIG meet-up to be organised in London called **Big Boost Monday**
- **Note :** Dream Factory have since removed their commitment to Big Boost Monday. It would be great to invite FINOS members to host so they can contribute of the FINOS DEI SIG initiative.

### Measurable Entry Points
- All FINOS events and meet-ups count towards DEI SIG measures and reporting
- Coaching, mentoring and training by FINOS Projects, SIGs and Maintainers at FINOS DEI meet-ups and events
- Community invited to participate in FINOS Projects by maintainers at FINOS DEI meet-ups and events
- DEI community invited to attend further FINOS events at FINOS DEI meet-ups and events
- DEI representatives invited to present at FINOS events and meet-ups
- Career coaches from FINOS members invited to present at FINOS events and meet-ups
- Potential internal FINOS member contributors invited to meet FINOS at DEI events

### Measuring and Reporting
- Demographic information will be recorded at the point of event registration
- New FINOS Project and SIG contributors will be communicated to FINOS to join the dots together on the individual DEI journey 

## FINOS and Community Partnerships
- FINOS DEI SIG should partner with established DEI groups to offer hosting, help and support in return for FINOS measurable recognition.

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming
