### ISSUE TITLE
March 1st 2023 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#18]
## Date
March 1st 2023 - 12:00pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Big Boost Monday - Retrospective and moving forward - Event Organisers and Synechron (FINOS Sponsors)
- [x] Code First Girls and NatWest Group Approach - How to leverage, open source angle(?) and next steps 
- [x] Finalising FINOS DEI SIG 2023 Goals and Objectives - https://github.com/finos/DEI-SIG/issues/17#issuecomment-1413767627
- [x] Financial Services Autism Hackathon - April 19-20th. It is a hybrid event, with the in-person venue in New York City at the EY Wavespace - @psmulovics
**Mission Statement**
Bring developers from the Financial Services industry together to demonstrate how innovative Microsoft technologies can transform autism treatment by tackling real world use cases provided by families and creating lasting open-source projects for the community.
**What does the Hackathon entail?**
2 days
70+ developers
5 use cases and infinity possibility to help people with using your technology skills!
Drop a note to [leo.junquera@ey.com](mailto:leo.junquera@ey.com) to add your company’s domain to the list.
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by mcleo-d** [comment]
Hello 👍🏻

**Comment by rhyddian** [comment]
👋 Rhyddian @ Citi

**Comment by eteridvalishvili** [comment]
Eteri @ FINOS

**Comment by DeclanOGorman** [comment]
Hi! Declan @ Natwest Group

**Comment by troups** [comment]
simon@soton uni and now also AllSpring global

**Comment by beekemarie** [comment]
Hi!

**Comment by slgscott** [comment]
better late than never :)

**Comment by slgscott** [comment]
Hi from 
@Scott Logic and @Marra

**Comment by psmulovics** [comment]
Links related to the FSI Autism Hackathon:

- Main page: [https://fsi-hack4autism.github.io/](https://fsi-hack4autism.github.io/)
- My blog with more details, downloadable flier, etc: [Announcing the 2023 Financial Services Autism Hackathon](https://dotneteers.net/announcing-the-2023-financial-services-autism-hackathon/)

**Comment by whykay** [comment]
Hello, finally made home, apologies for being late.

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming
