### ISSUE TITLE
April 5th 2023 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#19]
## Date
April 5th 2023 - 12:00pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Big Boost Mondays - Zngly Team
  - Citi (London), Dogpatch Labs (Dublin), Red Badger (London), Microsoft (Dublin / Ireland)
  - Feedback and Retrospective
  - Calls to Action 
- [ ] DEI SIG 2023 Goals and Objectives - DEI SIG Leads
  - Define what diversity at FINOS truly means. 
  - Create toolkits, guidelines and communications that provides the FINOS Governing Board, Projects, SIGS and Community guidance on how to engage FINOS DEI.
  - Horizontally scale FINOS Diversity, Equity and Inclusion across FINOS community and landscape.
  - Provide keynote and FINOS Community Award for FINOS Open Source in Finance Forum in NYC.
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by cm-howard** [comment]
Hello 👋🏼

**Comment by jevonbeck** [comment]
hello

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by niamhoparker** [comment]
hello

**Comment by ditomike** [comment]
Hello

**Comment by oscarwilson1999** [comment]
hello!

**Comment by eteridvalishvili** [comment]
Hello!

**Comment by beekemarie** [comment]
Forgot to comment here yesterday :)

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming
