### ISSUE TITLE
1st March 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#2]
## Date
Tuesday 1st March 2022 - 1pm ET / 6pm UK

## Untracked attendees
- Alli Villagra
- Keesa Schreane
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Keesa to present/plug event in next board meeting
- [ ] ...

## Action Items
- [x] Melinda forward Keesa slides for board meeting
- [x] Melinda work on blog post
- [x] Alexandra email intro Griz to Lynne
- [x] Invite Griz to next call
- [x] James to look into using Zoom for this SIG call instead of WebEx (for security reasons)

### WebEx info
**Meeting link:**
- https://finos.webex.com/finos/j.php?MTID=m8c68bf14e3fce3cc567ffabaf30288d0

**Meeting number:**
- 2552 137 1430

**Join by phone**
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll

**Access code:**
- 2552 137 1430

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by melindajoy** [comment]
hullo

**Comment by alstratigos** [comment]
Hi!

**Comment by cm-howard** [comment]
Hello 👋🏼

**Comment by mcleo-d** [comment]
Minutes
a
b
c

**Comment by esthersun2003** [comment]
hi

**Comment by troups** [comment]
@mcleo-d - sorry to miss the call earlier in the week, i'll aim to join next time
