### ISSUE TITLE
May 3rd 2023 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#20]
## Date
May 3rd 2023 - 12:00pm EST / 5pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Big Boost Mondays- Zngly and FINOS Update
  - **Retrospective**
    - London - April 24th at Red Badger
    - [Big Boost Mondays at Red Badger, London](https://tg.zngly.com/content/register-now-big-boost-mondays-london-red-badger/?s=red+badger)
  - **Future Events**
    - Dublin Monday 15th May
      - Microsoft and Technology University of Dublin - Student Expo
      - [Big Boost Mondays at Microsoft, Dublin](https://tg.zngly.com/znglist/big-boost-mondays-dublin-may-22nd-at-microsoft/?c=cG9zdDo5OTEwOTg=)
    - Belfast Monday 22nd May
      - Synechron and Ulster University - Student Expo 
      - [Big Boost Mondays at Synechron, Belfast](https://tg.zngly.com/znglist/big-boost-mondays-may-22nd-belfast/?c=cG9zdDo5OTExMzg=)
   - **Supporters so far ...** 
     - Citi, Code First Girls, Coding Grace, Deutsche Bank, Dogpatch Labs, EPAM, FINOS, gitHub, Goldman Sachs, Google, ING, LTSB, Microsoft, Mission Beyond, Morgan Stanley, NatWest, PwC, Red Badger, Red Hat, Rich Mix, Split, St Hilda's, Synechron, Tech She Can, Technology University Dublin, Turntable, Ulster University, Zngly
- FINOS board update and DEI SIG at FINOS Member Meeting, London
- How to fulfil DEI SIG 2023 Goals 
![2023Q2 - FINOS Governing Board Meeting](https://user-images.githubusercontent.com/6029572/235734061-b01bf146-692a-4b22-939b-bcbd6ee40140.jpg)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by jevonbeck** [comment]
Jevon Beckles - Scott Logic

**Comment by oscarwilson1999** [comment]
Oscar Wilson, Zngly

**Comment by MikeWilsonZngly** [comment]
Mike Wilson, Zngly

**Comment by beekemarie** [comment]
Beeke-Marie Nelke, GS

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming
