### ISSUE TITLE
July 5th 2023 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#21]
## Date
July 5th 2023 - 12:00pm EST / 5pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Citi Lunch Retrospective and Actions - Big Boost Mondays, Tech Gateway, Plus More!
- [x] FINOS Member Meeting, London retrospective
    - How did it go? 
    - What did we learn for OSFF on 1st Nov? 
- [ ] CFP Still Open - FINOS Open Source in Finance Forum 1st Nov
- [ ] FINOS board meeting July 19th at Goldman Sachs, London
- [ ] How to fulfil DEI SIG 2023 Goals 
![2023Q2 - FINOS Governing Board Meeting](https://user-images.githubusercontent.com/6029572/235734061-b01bf146-692a-4b22-939b-bcbd6ee40140.jpg)
- [ ] New FINOS project contribution proposal [Accessibility Theme Builder](https://github.com/finos/community/issues/273)
  - [ ] Engage on the GitHub
  - [ ] Looking for co-authors for a blogpost 
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/98492160513
Meeting ID: 984 9216 0513
Passcode: 691166

**Comment by oscarwilson1999** [comment]
Oscar Wilson - Zngly

**Comment by TadhgWilson** [comment]
Tadhg Wilson - Zngly

**Comment by KaajalAminSharma** [comment]
Kaajal- Citi

**Comment by jevonbeck** [comment]
Jevon - Scott Logic

**Comment by whykay** [comment]
Vicky Twomey-Lee - Coding Grace / PyLadies Dublin / GameCraft
Other 🧢: Python Software Foundation Grants Working Group / EuroPython Society Board / Women Who Code Dublin Alumni

**Comment by ditto-vlad** [comment]
Vlad - Zngly 🧑‍💻

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏦

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by beekemarie** [comment]
Beeke-Marie Nelke / GS

**Comment by JamieSlome** [comment]
Jamie Slome from Citi 🍰

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming
