### ISSUE TITLE
3rd January 2024 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by Perelmuter** [finos/DEI-SIG#28]
## Date
2024 JAN 3 - 12:00pm ET / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review Board meeting materials (Peter)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Eteri to find out if DEI SIG chairs can join Jan 17th Board meeting for Peter's presentation
- [ ] Mike to present on BBM plans for 2024 in next DEI SIG meeting. Need to cover as well where DEI SIG can help
- [ ] Peter to forward board meeting dry run meetings to Beeke/ Mike so that we can help to finalize.

## Action Items

See above.

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/94969868675
Meeting ID: 949 6986 8675
Passcode: 184472

**Comment by mcleo-d** [comment]
James McLeod / NatWest

**Comment by beekemarie** [comment]
Beeke-Marie Nelke / GS

**Comment by PaulaPaul** [comment]
Closed as part of DEI SIG project board grooming
