### ISSUE TITLE
03/06/2024 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by ritachaturvedi** [finos/DEI-SIG#34]
## Date
03/06/2024 - 12:00pm EST / 5pm GMT

Announcement - 
After many invaluable contributions to the DEI SIG, Beeke has made a decision to step down from the Co-Chair position to focus on other priorities. She will stay on as a SIG member and continue to contribute in that capacity. 
The SIG would like to thank Beeke for her efforts towards significant achievements of the SIG!

This opens up a Co-Chair position on the SIG. Any members interested in taking on the role should reach out to Rimma Perelmuter. 

Agenda:

1. Roll call 
2. Beeke's announcement and new Co-Chair selection - Rita and Rimma
3. Proposals for London OSFF - Rimma
4. Proposals for GHC submission - Paula
5. Open discussion - All

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Agenda item 1
- [ ] Agenda item 2
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/94969868675
Meeting ID: 949 6986 8675
Passcode: 184472

**Comment by whykay** [comment]
A quick question, the latest cal invite says this meeting is cancelled? It's been updated a few times before, but I want to check if this meeting is going ahead or not?

**Comment by Perelmuter** [comment]
➡️ A reminder to Join our next DEI SIG meeting on Wednesday March 7th TODAY at 5 pm UK](https://lnkd.in/esDp4epY) to shape our expanded vision 

A big thank you to @beekemarie for excellent work to get things off the ground a staying on as a contributor !

If you are interested in serving as ourDEI SIG co-chair please declare your interest and feel free to reach out to me @Rimma@finos.org with questions!

There will also be numerous contributor opportunities discussed on the call so a great opp to drive forward our ambitious agenda:)

**Comment by PaulaPaul** [comment]
Thank you @beekemarie! 
@ritachaturvedi and @Rimma I am interested in the co-chair role - see you on today's call and please let me know if you need additional information from me. See you soon-

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by psmulovics** [comment]
Looking forward to have you, @PaulaPaul !

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by PaulaPaul** [comment]
Paula Paul (@PaulaPaul) - Greyshore

**Comment by lwnoble** [comment]
Lise Noble - Discover

**Comment by whykay** [comment]
Vicky Twomey-Lee - Coding Grace / PyLadies Dublin / GameCraft
Other 🧢: Python Software Foundation Grants Working Group / EuroPython Society Board / Women Who Code Dublin Alumni

**Comment by rhyddian** [comment]
👋 @rhyddian Olds - Citi

**Comment by beekemarie** [comment]
Beeke-Marie Nelke / GS

**Comment by JinanMartiuk** [comment]
Jinan Martiuk -Appian - Interested in DEI events

**Comment by mcleo-d** [comment]
James McLeod / NatWest Group

**Comment by KaajalAminSharma** [comment]
Kaajal - Citi

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by ritachaturvedi** [comment]
Rita Chaturvedi/Morgan Stanley

**Comment by Perelmuter** [comment]
Rimma Perelmuter-FINOS

**Comment by PaulaPaul** [comment]
Approved on the DEI SIG call, April 3
