### ISSUE TITLE
03 Apr 2024 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by PaulaPaul** [finos/DEI-SIG#36]
## Date
20240403 - 12:00pm EST / 5pm GMT

## Attendees
- Comment on this issue with the following information
  - Fullname, Affiliation, (optional) GitHub username
- Those unable to add a comment on the GitHub issue can be listed below for meeting minutes
  - ... 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes ( #34 )
- [x] Update on Co-Chairs - Rita and Rimma @Perelmuter https://github.com/orgs/finos/projects/94
- [x] Community Updates
  - Grace Hopper Celebration Updates - @PaulaPaul 
    - Abstracts have been submitted for Open Source Day, and for a Panel Session! Thank you Rimma and Lise! ( #31)
    - DEI SIG Options for FINOS presence at GHC - Help Wanted ( #41 )
      - Ask member companies to allow for FINOS presence and swag in their GHC booths
      - Is there a member company with a large office in Philadelphia that could be used for a FINOS BBM / Ambassador event?
         - Share the $19,000 sponsorship for a 'Sponsor Hosted Event Listing' among member companies participating in GHC
         - Benefits include: Sponsor Hosted Event listed in GHC Agenda featuring Sponsor name and logo, event title, time, date, detailed description of event, including how to attend/RSVP, and transportation to event and 1 Lead Retrieval License to collect attendee data at Sponsor Hosted Event 
  - GAAD and Microsite Update - Paula  - Help Wanted ( #43 )  
  - OSFF session update - James ( #35 )
- [ ] DEI Metrics and Call for Maintainers - 
  - Metrics and best practices with CHAOSS (DEI Badging), LF "All In" projects (need volunteers) #33
  - Engaging Member DEI experts to collect best practices (need volunteers) #44
  - DEI SIG - Call for (GitHub) Maintainers #46 
  - Request for a 2024 BBM schedule of events: #39 , #40 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Sergio and Paula - co chairs

## Action Items
- [ ] @PaulaPaul to follow up on issue to engage FINOS projects for OSD
- [ ] @Perelmuter to confirm if LF will have a booth we can co-locate with, and engage AI Readiness SIG
- [ ] ...

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/94969868675
Meeting ID: 949 6986 8675
Passcode: 184472

For more information or to contact the group email:
[diversity-inclusion-committee@finos.org](mailto:diversity-inclusion-committee@finos.org)

Resources:
[DEI SIG Github repo](https://www.google.com/url?q=https://github.com/finos/DEI-SIG/&sa=D&source=calendar&ust=1711893502059351&usg=AOvVaw3oPu8t0x8AxOo06RCBcVqE)

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by Perelmuter** [comment]
Rimma - FINOS

**Comment by PaulaPaul** [comment]
Paula Paul - Greyshore (@PaulaPaul)

**Comment by mcleo-d** [comment]
James McLeod / Lee-Ann Sansom from NatWest Group

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by ritachaturvedi** [comment]
Rita CHATURVEDI Morgan Stanley

**Comment by PaulaPaul** [comment]
Approved during May 1 SIG call

**Comment by PaulaPaul** [comment]
Issue closed post review on the May SIG call
