### ISSUE TITLE
05 APR 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by melindajoy** [finos/DEI-SIG#4]
## Date
20220405 - time

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] 15m (Gab) - Checkin in on H1 DEI OKRs (announcement of SIG, measuring of Community composition/diversity)
- [x] 15m (Grizz) - Marketing support / channels 
- [x] 5m - Coding Black Females April 12th call with Founder - Chris Howard to lead (Partnerships)
- [x] 5m - Any substantial update / progress ahead 4/20 Governing Board meeting 
- [x] AOB, Q&A & Adjourn (5mins)

**Notes**

- Catherine Zhai from Citi will be co-leading Metrics stream with Esther Sun.
- Gathering the project diversity composition - possible at event level but not at project level.
- Next July board meeting is the next big update
- A blog post to let people know there's a DEI SIG.
- Beeke-Marie & Lynne would like to set up a meeting with the folks organising the conference to make sure there's a diversity track. They've gotten in touch with the right people at LF and also around awards/understanding the event.
- Hannah Pretswell is new co-lead of marketing & events in EMEA. Sr Tester at Scott Logic. Done lots with STEM research.
- Meet up happening in London on the April 20th (Griz and Niamh will both be in London the week of April 18).
- OSFF London is July 13, 2022
- Grizz - marketing can help with cross-promotion and the logistics of setting up call events, or recorded content posted onto the blog, etc.  
- One of the biggest pain points: hard to find diverse speakers, who wants to do articles?
- What FINOS Marketing CAN'T do: come up with the concept and create content. 
- One idea Grizz has is a quarterly DEI event.
- Member digest will go out after board meeting on April 26th. Digest often points to the blog.
- Lynne's branding question: will it be Linux or FINOS? FINOS first but rely on Linux in some instances.

## Decisions Made
- [ ] We will announce/promote the DEI SIG on the blog
- [ ] Next big update is July Board meeting - Keesa will promote her Q3 webinar event

## Action Items
- [ ] Esther and Catherine - Working with LF legal team to collect data. Level of granularity is male vs female, URM vs not. Will give us another OKR update next monthly meeting.

### WebEx info
**Meeting link:**
- https://finos.webex.com/finos/j.php?MTID=m8c68bf14e3fce3cc567ffabaf30288d0

**Meeting number:**
- 2552 137 1430

**Join by phone**
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll

**Access code:**
- 2552 137 1430

**Comment by cm-howard** [comment]
Hello 👋🏼

**Comment by grizzwolf** [comment]
Grizz Griswold - present!

**Comment by niamhoparker** [comment]
Present - great to meet you all.

**Comment by jevonbeck** [comment]
present

**Comment by beekemarie** [comment]
present

**Comment by alstratigos** [comment]
Hello!

**Comment by catherinezhai** [comment]
Hello, pleasure to meet everyone!

**Comment by melindajoy** [comment]
+ Rita Chaturvedi
