### ISSUE TITLE
Finalize selection of co-chairs, due to open role

### ISSUE THREAD

**Issue by PaulaPaul** [finos/DEI-SIG#47]
@beekemarie has decided to remain involved with the DEI-SIG but will be stepping down from the co-chair role-

To fill the co-chair role, @Perelmuter posted in the [minutes for the March DEI SIG](https://github.com/finos/DEI-SIG/issues/34) that the call for co-chairs was open, and that interested individuals should respond or contact her directly.

This issue can be closed when the selection of co-chair(s) is complete.

**Comment by Perelmuter** [comment]
Thanks for resharing @PaulaPaul - we are looking to resolve this tomorrow April 3rd -As shared on March 18th, Individuals interested in the vacant Co-Chair position should contact me at Rimma@finos.org noting their background and ability to contribute.
 

Before putting themselves forward, It is important that individuals understand the time commitment and accountability requirements of the role.  The Co-Chair role is operational akin to COO responsibilities: Here is a description of the [OSR SIG Leadership responsibilities](https://osr.finos.org/docs/about#leadership) as an example.  In addition to meeting planning and execution, it is expected that co-chairs will co-share preparation of the agenda/minutes/action items from the call as the SIG needs to be self-sustaining. In addition, the Co-Chairs will need to monitor and be responsive to the standard communications channels (Slack and GitHub, or others as determined by the Chair and Co-Chairs), and communicate their availability on standard channels when they are time constrained or out of office. 
 

It is important that there is clarity on role differentiation and shared responsibility to ensure that the SIGs are run effectively and can become self-sustaining.    If more than one candidate emerges, we may consider adding more than two co-chairs.


A clarification WRT to Co-Chair Selection from FINOS Executive Director [Gabriele Columbro](mailto:gabriele.columbro@finos.org) - As the DEI SIG expands its remit, we are open to multiple co-chairs.  We would ideally like to see co-chairs selected by the SIG based on their stated contributions, experience  and ability to dedicate time to co-chair responsibilities. Elections are time-consuming to administer so ideally we would look to gain consensus on co-chairs with complimentary contributions on the next SIG call taking place on April 3rd.

Furthermore, exciting  opportunities for important issues are listed under 'to-do' here: https://github.com/orgs/finos/projects/94/views/1 -  we would be excited to see volunteers step forward for these roles to spearhead and take forward!

**Comment by sergiobettencourt** [comment]
Hello All -- I hope you're all well.

My name is Sérgio Bettencourt and I have been actively involved in the DEI SIG for the past year representing Citi.

Following conversation with Rimma, I am submitting myself as candidate for Co-Chair of the SIG.

Though my background is primarily aligned to Financial Services and Technology, I have a strong history in both Human Capital and Diversity, Equity and Inclusion spaces and I am passionate about building and motivating communities toward addressing issues of greatest impact.

With respect to experience, I have spent most of my career involved in some leadership capacity across organizations aligned toward improving the experience of individuals of diverse communities, most recently within Citi as a Co-Chair of an internal global strategy focusing on addressing opportunity gaps for Black/Latinx professionals and their allies. In this role I am responsible for internal programming aligned to building community, resource retention, professional development, and organizing flagship events such as an annual conference and heritage aligned development and networking events. The experience has been one of the highlights of my career and has fundamentally change my experience of work and how I see myself as a professional.

Please be sure to reach out to me should you have any questions and I hope I can count on your support.

I look forward to working with each of you as we move forward.

Thank you.

Sérgio

**Comment by PaulaPaul** [comment]
Sérgio Bettencourt and @PaulaPaul were selected as co-chairs on the DEI SIG call, April 3rd :)
