### ISSUE TITLE
03 MAY 2022 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by melindajoy** [finos/DEI-SIG#5]
## Date
20220503 

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Esther: Checkin in on H1 DEI OKRs
- [x] Jevon Beckles: Campfire idea
- [x] Chris Howard: CBF collaboration
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [x] Add 2022 OKR slide (from Jan board meeting) for easy reference @alstratigos 
- [x] Add slide that shows work stream leads @alstratigos 
- [ ] Put forth in mailing list any podcast ideas and/or requests (DEI group) 
- [ ] Determine if funds are available from FINOS @alstratigos 
- [ ] Get monthly meeting on Community Calendar @alstratigos @TheJuanAndOnly99 
- [ ] Add monthly meeting to This Week at FINOS (TWAF) @alstratigos @Julia-Ritter 

**ZOOM details:**
Join Zoom Meeting
[https://zoom.us/j/99897744347?pwd=OTcrM21MZ1RFMzBYYnJ6cUN3SjVGZz09](https://www.google.com/url?q=https://zoom.us/j/99897744347?pwd%3DOTcrM21MZ1RFMzBYYnJ6cUN3SjVGZz09&sa=D&source=calendar&ust=1652028671535999&usg=AOvVaw2xMcbQHU3QKcV2bNaqxC1w)

Meeting ID: 998 9774 4347
Passcode: 931122
One tap mobile
+16699006833,,99897744347# US (San Jose)
+13462487799,,99897744347# US (Houston)

**Comment by cm-howard** [comment]
Hello all 👋🏼

**Comment by beekemarie** [comment]
Here

**Comment by alstratigos** [comment]
Hello!

**Comment by hannimator** [comment]
Here :)

**Comment by alstratigos** [comment]
Hello from Rita Chaturvedi (working internally to get GH permissions)
