### ISSUE TITLE
FINOS and Zngly Partnership Event – “Tech Gateway”

### ISSUE THREAD

**Issue by mcleo-d** [finos/DEI-SIG#8]
**Welcome to “Tech Gateway” a day program of DEI events held in London, curated, and produced in partnership of FINOS and Zngly that…**

- Bring together under-represented groups and opportunities in tech (and the city)
- With a particular focus on pathways into the tech industry for non-graduates
- Inform, inspire, and engage with a showcase of diversity of talent, and the diversity of opportunities

**Who will be involved?** 

- Students, under-represented groups, interested parties, and the curious 
- Industry professionals, senior stakeholders, allies and sponsors 
- Community outreach in Hackney / Tower Hamlets 

**How will it work?**

A mixture of three in-person events hosted during the day at city offices / locations, with a grand finale and gathering at Rich Mix for an evening of talks (filmed for on-demand), connecting and fun. Including ‘Tech Explore’ booths, swag, meet grad / intern / apprentices. 

**Day Program - 22nd September 2022**

- 10.00am – 11.00am – Introducing Tech & Deutsche Bank
  - DEI at Deutsche Bank
  - What is tech and the role it plays at DB
  - An inspiring story

- 12.00pm – 1.30pm – Lunchtime stories by ING
  - Google
  - Vendor
  - Deloitte

- 3.00pm – 4.00pm – Afternoon session (vendor?)
  - Coding and Testing
  - UI & Design 
  - Sales & Relationship Management 
  - Infrastructure & Cyber

**Evening Event / Finale - Campfire**

- 6.00pm – 7.00pm – Rich Mix, doors open
- 7.00pm – 8.00pm – Panel discussion
  - FINOS, Scott Logic, DB, ING, Google, Deloitte , [Charlene Hunter](https://uk.linkedin.com/in/charlenephunter)
- 8.00pm – 10.00pm – Networking with music, pizza, drinks – ‘Tech Explore’

**Comment by mcleo-d** [comment]
Find the local DEI groups in FINOS members as they should be embedded in the local London communities. This also includes Google.

Rich Mix also has a network to leverage. Rich Mix has initial investment from Deutsche Bank.

**Comment by mcleo-d** [comment]
What we need from FINOS member banks and tech companies?

**Comment by mcleo-d** [comment]
How much will this cost and what should the budget be?

**Comment by cm-howard** [comment]
Let me know how I can support on this as very keen to get involved. Could potentially support with the following:

- Connecting to D&I Leads across Tech & FS companies in London
- Linking up with diversity non-profits such as my own org Intertech
- Consider if EPAM may be a suitable candidate for the vendor session in the afternoon (Liverpool St)
- Promote the event via D&I communities within London

Thanks 👍🏼

**Comment by mcleo-d** [comment]
Hi Chris,

It would be awesome to have your involvement in the event organising. 

I'm on holiday at the moment, but will absolutely connect you to the group when I'm back. 

Thanks for your support. 

James.

**Comment by mcleo-d** [comment]
@cm-howard 

I have just added you to the organisers meeting that should now appear in your calendar. 

James.

**Comment by cm-howard** [comment]
Thanks @mcleo-d - Invite received and looking forward to supporting where I can.
